HelloWorld
HelloWorld

diff --git a/package/lean/luci-app-vssr/root/usr/bin/vssr-rules b/package/lean/luci-app-vssr/root/usr/bin/vssr-rules
--- a/package/lean/luci-app-vssr/root/usr/bin/vssr-rules
+++ b/package/lean/luci-app-vssr/root/usr/bin/vssr-rules
@@ -75,41 +75,41 @@ flush_r() {
 
 ipset_r() {
 	ipset -N gmlan hash:net 2>/dev/null
-	for ip in $LAN_GM_IP; do ipset -! add gmlan $ip ; done
-	
-	if [ "$RUNMODE" = "router" ] ;then
-	ipset -! -R <<-EOF || return 1
-		create ss_spec_wan_ac hash:net
-		$(gen_iplist | sed -e "s/^/add ss_spec_wan_ac /")
-EOF
-	ipset -N gfwlist hash:net 2>/dev/null
-	$IPT -N SS_SPEC_WAN_AC 
-	$IPT -I SS_SPEC_WAN_AC -d $server -j RETURN
-	$IPT -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
-	$IPT -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-	
-	elif [ "$RUNMODE" = "gfw" ] ;then
-	ipset -N gfwlist hash:net 2>/dev/null
-	$IPT -N SS_SPEC_WAN_AC
-	$IPT -A SS_SPEC_WAN_AC -m set --match-set gfwlist dst -j SS_SPEC_WAN_FW	
-	$IPT -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW	
-	$IPT -A SS_SPEC_WAN_AC -m set --match-set china dst -j RETURN
-	$IPT -I SS_SPEC_WAN_AC -d $server -j RETURN
-	
-	elif [ "$RUNMODE" = "oversea" ] ;then
-	ipset -N oversea hash:net 2>/dev/null
-	$IPT -N SS_SPEC_WAN_AC
-	ipset -N gmlan hash:net 2>/dev/null
-	for ip in $LAN_GM_IP; do ipset -! add gmlan $ip ; done
-	$IPT -A SS_SPEC_WAN_AC -m set --match-set china dst -j SS_SPEC_WAN_FW
-	$IPT -I SS_SPEC_WAN_AC -d $server -j RETURN
-	
-	elif [ "$RUNMODE" = "all" ] ;then
-	$IPT -N SS_SPEC_WAN_AC
-	$IPT -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-	$IPT -I SS_SPEC_WAN_AC -d $server -j RETURN
-	
-	fi
+	for ip in $LAN_GM_IP; do ipset -! add gmlan $ip; done
+	case "$RUNMODE" in
+	router)
+		ipset -! -R <<-EOF || return 1
+			create ss_spec_wan_ac hash:net
+			$(gen_iplist | sed -e "s/^/add ss_spec_wan_ac /")
+		EOF
+		ipset -N gfwlist hash:net 2>/dev/null
+		$IPT -N SS_SPEC_WAN_AC
+		$IPT -I SS_SPEC_WAN_AC -p tcp ! --dport 53 -d $server -j RETURN
+		$IPT -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
+		$IPT -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
+		;;
+	gfw)
+		ipset -N gfwlist hash:net 2>/dev/null
+		$IPT -N SS_SPEC_WAN_AC
+		$IPT -A SS_SPEC_WAN_AC -m set --match-set gfwlist dst -j SS_SPEC_WAN_FW
+		$IPT -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW
+		$IPT -A SS_SPEC_WAN_AC -m set --match-set china dst -j RETURN
+		$IPT -I SS_SPEC_WAN_AC -p tcp ! --dport 53 -d $server -j RETURN
+		;;
+	oversea)
+		ipset -N oversea hash:net 2>/dev/null
+		$IPT -N SS_SPEC_WAN_AC
+		ipset -N gmlan hash:net 2>/dev/null
+		for ip in $LAN_GM_IP; do ipset -! add gmlan $ip; done
+		$IPT -A SS_SPEC_WAN_AC -m set --match-set china dst -j SS_SPEC_WAN_FW
+		$IPT -I SS_SPEC_WAN_AC -p tcp ! --dport 53 -d $server -j RETURN
+		;;
+	all)
+		$IPT -N SS_SPEC_WAN_AC
+		$IPT -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
+		$IPT -I SS_SPEC_WAN_AC -p tcp ! --dport 53 -d $server -j RETURN
+		;;
+	esac
 	
 	ipset -N fplan hash:net 2>/dev/null
 	for ip in $LAN_FP_IP; do ipset -! add fplan $ip ; done
@@ -128,14 +128,14 @@ EOF
 
 fw_rule() {
 	$IPT -N SS_SPEC_WAN_FW
-  $IPT -A SS_SPEC_WAN_FW -d 0.0.0.0/8 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 10.0.0.0/8 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 127.0.0.0/8 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 169.254.0.0/16 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 172.16.0.0/12 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 192.168.0.0/16 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 224.0.0.0/4 -j RETURN
-  $IPT -A SS_SPEC_WAN_FW -d 240.0.0.0/4 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 0.0.0.0/8 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 10.0.0.0/8 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 127.0.0.0/8 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 169.254.0.0/16 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 172.16.0.0/12 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 192.168.0.0/16 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 224.0.0.0/4 -j RETURN
+	$IPT -A SS_SPEC_WAN_FW -d 240.0.0.0/4 -j RETURN
 	$IPT -A SS_SPEC_WAN_FW  -p tcp $PROXY_PORTS \
 		-j REDIRECT --to-ports $local_port 2>/dev/null || {
 		loger 3 "Can't redirect, please check the iptables."
@@ -147,37 +147,37 @@ fw_rule() {
 ac_rule() {
 	if [ -n "$LAN_AC_IP" ]; then
 		case "${LAN_AC_IP:0:1}" in
-			w|W)
-				MATCH_SET="-m set --match-set ss_spec_lan_ac src"
-				;;
-			b|B)
-				MATCH_SET="-m set ! --match-set ss_spec_lan_ac src"
-				;;
-			*)
-				loger 3 "Bad argument \`-a $LAN_AC_IP\`."
-				return 2
-				;;
+		w | W)
+			MATCH_SET="-m set --match-set ss_spec_lan_ac src"
+			;;
+		b | B)
+			MATCH_SET="-m set ! --match-set ss_spec_lan_ac src"
+			;;
+		*)
+			loger 3 "Bad argument \`-a $LAN_AC_IP\`."
+			return 2
+			;;
 		esac
 	fi
 	IFNAME=$(uci get -P/var/state network.lan.ifname 2>/dev/null)
 	ipset -! -R <<-EOF || return 1
 		create ss_spec_lan_ac hash:net
 		$(for ip in ${LAN_AC_IP:1}; do echo "add ss_spec_lan_ac $ip"; done)
-EOF
+	EOF
 	$IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET \
-		-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
+	-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
 	if [ "$OUTPUT" = 1 ]; then
 		$IPT -I OUTPUT 1 -p tcp $EXT_ARGS \
-			-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
+		-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
 	elif [ "$OUTPUT" = 2 ]; then
 		ipset -! -R <<-EOF || return 1
-		create ssr_gen_router hash:net
-		$(gen_spec_iplist | sed -e "s/^/add ssr_gen_router /")
-EOF
+			create ssr_gen_router hash:net
+			$(gen_spec_iplist | sed -e "s/^/add ssr_gen_router /")
+		EOF
 		$IPT -N SS_SPEC_ROUTER && \
 		$IPT -A SS_SPEC_ROUTER -m set --match-set ssr_gen_router dst -j RETURN && \
 		$IPT -A SS_SPEC_ROUTER -j SS_SPEC_WAN_FW
-		$IPT -I OUTPUT 1 -p tcp -m comment --comment "$TAG" -j SS_SPEC_ROUTER	
+		$IPT -I OUTPUT 1 -p tcp -m comment --comment "$TAG" -j SS_SPEC_ROUTER
 	fi
 	return $?
 }
@@ -188,44 +188,44 @@ tp_rule() {
 	ip route add local 0.0.0.0/0 dev lo table 100
 	local ipt="iptables -t mangle"
 	$ipt -N SS_SPEC_TPROXY
+	$ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN
 	$ipt -A SS_SPEC_TPROXY -p udp --dport 53 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 0.0.0.0/8 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 10.0.0.0/8 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 127.0.0.0/8 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 169.254.0.0/16 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 172.16.0.0/12 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 192.168.0.0/16 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 224.0.0.0/4 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d 240.0.0.0/4 -j RETURN
-  $ipt -A SS_SPEC_TPROXY -p udp -d $SERVER -j RETURN
-  
-  $ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set fplan src \
+	$ipt -A SS_SPEC_TPROXY -p udp -d 0.0.0.0/8 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 10.0.0.0/8 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 127.0.0.0/8 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 169.254.0.0/16 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 172.16.0.0/12 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 192.168.0.0/16 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 224.0.0.0/4 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp -d 240.0.0.0/4 -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp ! --dport 53 -d $server -j RETURN
+	$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set fplan src \
+	-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
+	case "$RUNMODE" in
+	router)
+		$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-  
-	if [ "$RUNMODE" = "router" ] ;then
-	$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china dst \
+		$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set ! --match-set ss_spec_wan_ac dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set ! --match-set ss_spec_wan_ac dst \
+		;;
+	gfw)
+		$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set china dst -j RETURN
+		$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	
-	elif [ "$RUNMODE" = "gfw" ] ;then
-	$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set china dst -j RETURN
-	$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set gmlan src -m set ! --match-set china dst \
+		$ipt -A SS_SPEC_TPROXY -p udp -m set $PROXY_PORTS --match-set gfwlist dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	$ipt -A SS_SPEC_TPROXY -p udp -m set $PROXY_PORTS --match-set gfwlist dst \
+		;;
+	oversea)
+		$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set china dst \
 		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-		
-	elif [ "$RUNMODE" = "oversea" ] ;then
-	$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -m set --match-set china dst \
-		-j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	
-	elif [ "$RUNMODE" = "all" ] ;then
-	$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
-	fi	
-		
+		;;
+	all)
+		$ipt -A SS_SPEC_TPROXY -p udp $PROXY_PORTS -j TPROXY --on-port "$LOCAL_PORT" --tproxy-mark 0x01/0x01
+		;;
+	esac
 	$ipt -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p udp $EXT_ARGS $MATCH_SET \
-		-m comment --comment "$TAG" -j SS_SPEC_TPROXY
-	
+	-m comment --comment "$TAG" -j SS_SPEC_TPROXY
 	return $?
 }
 
@@ -376,14 +376,14 @@ if [ -z "$server" -o -z "$local_port" ]; then
 	usage 2
 fi
 
-if [ "$TPROXY" = 1 ]; then
+if [ "$TPROXY" == 1 ]; then
 	SERVER=$server
 	LOCAL_PORT=$local_port
-elif [ "$TPROXY" = 2 ]; then
+elif [ "$TPROXY" == 2 ]; then
 	: ${SERVER:?"You must assign an ip for the udp relay server."}
 	: ${LOCAL_PORT:?"You must assign a port for the udp relay server."}
 fi
 
 flush_r && fw_rule && ipset_r && ac_rule && tp_rule && gen_include
-[ "$?" = 0 ] || loger 3 "Start failed!"
+[ "$?" == 0 ] || loger 3 "Start failed!"
 exit $?
