bcm27xx-utils: update to 2026.06.21
Signed-off-by: coolsnowwolf <coolsnowwolf@gmail.com>

diff --git a/package/utils/bcm27xx-utils/patches/0001-raspinfo-adapt-to-OpenWrt.patch b/package/utils/bcm27xx-utils/patches/0001-raspinfo-adapt-to-OpenWrt.patch
--- a/package/utils/bcm27xx-utils/patches/0001-raspinfo-adapt-to-OpenWrt.patch
+++ b/package/utils/bcm27xx-utils/patches/0001-raspinfo-adapt-to-OpenWrt.patch
@@ -8,66 +8,23 @@ Content-Transfer-Encoding: 8bit
 
 Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
 ---
- raspinfo/raspinfo | 186 ++++------------------------------------------
- 1 file changed, 13 insertions(+), 173 deletions(-)
+ raspinfo/raspinfo | 206 +++-------------------------------------------
+ 1 file changed, 11 insertions(+), 195 deletions(-)
 
 --- a/raspinfo/raspinfo
 +++ b/raspinfo/raspinfo
-@@ -1,4 +1,4 @@
--#!/bin/bash
-+#!/bin/sh
+@@ -8,173 +8,13 @@
  
- # Some of the regex's used in sed
- # Catch basic IP6 address   "s/\([0-9a-fA-F]\{1,4\}:\)\{7,7\}[0-9a-fA-F]\{1,4\}/y.y.y.y.y.y.y.y/g"
-@@ -6,147 +6,6 @@
- # IP4 d.d.d.d decimal	    "s/\([0-9]\{1,3\}\.\)\{3,3\}[0-9]\{1,3\}/x.x.x.x/g"
- # mac address	            "s/\([0-9a-fA-F]\{2,2\}\:\)\{5,5\}[0-9a-fA-F]\{2,2\}/m.m.m.m/g"
+ alias filter="sed -e 's/\([0-9a-fA-F]\{1,4\}:\)\{7,7\}[0-9a-fA-F]\{1,4\}/y.y.y.y.y.y.y.y/g' | sed -e 's/[0-9a-fA-F]\{1,4\}:\(:[0-9a-fA-F]\{1,4\}\)\{1,4\}/y::y.y.y.y/g' | sed -e 's/\([0-9]\{1,3\}\.\)\{3,3\}[0-9]\{1,3\}/x.x.x.x/g' | sed -e 's/\([0-9a-fA-F]\{2,2\}\:\)\{5,5\}[0-9a-fA-F]\{2,2\}/m.m.m.m/g'"
  
--
 -display_info_drm() {
--   # If running X then can use xrandr, otherwise
--   # dump the /sys/class entries for the displays
--   if command -v xrandr > /dev/null &&
--      DISPLAY=${DISPLAY:-:0} xrandr --listmonitors &>/dev/null;
--   then
--      echo "Running (F)KMS and X"
--      echo
--
--      DISPLAY=${DISPLAY:-:0} xrandr --verbose
--   else
--      echo "Running (F)KMS, console"
--      echo
--
--      for card in /sys/class/drm/card[0-9]-*;
--      do
--         echo $card
--
--         # if kmsprint isn't installed print basic mode info
--         if ! command -v kmsprint > /dev/null; then
--            if [ -f $card/modes ];
--            then
--               cat $card/modes
--            else
--               echo "No modes found"
--            fi
--         fi
--
--         if [ -f $card/edid ];
--         then
--            base64 $card/edid
--         else
--            echo "No EDID found"
--         fi
--         echo
--      done
--   fi
--
 -   # kmsprint is more useful, but not always installed
--   echo
 -   if command -v kmsprint > /dev/null; then
 -      kmsprint
 -      echo
 -      kmsprint -m
+-      echo
+-      kmsprint -p
 -   else
 -      echo "kmsprint is not installed. Install with: sudo apt install kms++-utils"
 -   fi
@@ -75,38 +32,61 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
 -   echo
 -
 -   # dump the /sys/class entries for the displays
+-   for card in /sys/class/drm/card[0-9]-*;
+-   do
+-      echo $card
+-
+-      if ! command -v kmsprint > /dev/null; then
+-         if [ -f $card/modes ];
+-         then
+-            cat $card/modes
+-         else
+-            echo "No modes found"
+-         fi
+-         echo
+-      fi
+-
+-      if [ -f $card/edid ];
+-      then
+-         base64 $card/edid
+-      else
+-         echo "No EDID found"
+-      fi
+-      echo
+-   done
+-
+-   # dump the /sys/kernel/debug entries for the displays
 -   cardfound=0
 -   for card in `seq 0 9`;
 -   do
 -      if sudo test -f "/sys/kernel/debug/dri/${card}/state";
 -      then
--        for hdmi in 0 1;
--        do
--         if sudo test -f "/sys/kernel/debug/dri/${card}/hdmi${hdmi}_regs";
--         then
--            echo "HDMI${hdmi}: $(sudo cat /sys/kernel/debug/dri/$card/hdmi${hdmi}_regs | grep HOTPLUG)"
+-         for hdmi in 0 1;
+-         do
+-            if sudo test -f "/sys/kernel/debug/dri/${card}/hdmi${hdmi}_regs";
+-            then
+-               echo "HDMI${hdmi}: $(sudo cat /sys/kernel/debug/dri/$card/hdmi${hdmi}_regs | grep HOTPLUG)"
+-            fi
+-         done
+-         echo
+-         # dump the state if we don't have kmsprint
+-         if ! command -v kmsprint > /dev/null; then
+-            echo "/sys/kernel/debug/dri/$card/state:"
+-            sudo cat "/sys/kernel/debug/dri/$card/state"
+-            echo
 -         fi
--      done
--      echo
--      echo "/sys/kernel/debug/dri/$card/state:"
--      sudo cat "/sys/kernel/debug/dri/$card/state"
--      echo
--      cardfound=1
+-         cardfound=1
 -      fi
 -   done
--   if [ "$cardfound" == "0" ];
+-   if [ "$cardfound" = "0" ];
 -   then
 -      echo "kms state not found"
+-      echo
 -   fi
--   echo
--
 -}
 -
 -display_info_legacy() {
 -   # Legacy mode
--   echo "Running Legacy framebuffer"
--   echo
--
 -   for card in `seq 0 9`;
 -   do
 -      F="/dev/fb${card}"
@@ -117,30 +97,63 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
 -      fi
 -   done
 -
--   disps=`tvservice -l | awk '/Display Number/{print substr($3,1,1)}'`
+-   if command -v tvservice > /dev/null; then
+-      disps=`tvservice -l | awk '/Display Number/{print substr($3,1,1)}'`
 -
--   tmp=$(mktemp)
+-      tmp=$(mktemp)
 -
--   for display in $disps
--   do
+-      for display in $disps
+-      do
+-         echo
+-         echo "Display: " $display
+-
+-         tvservice -v $display -s
+-         tvservice -v $display -n
+-         tvservice -v $display -m CEA
+-         tvservice -v $display -m DMT
+-
+-         echo
+-         tvservice -v $display -d $tmp > /dev/null
+-         base64 $tmp
+-         echo
+-      done
+-
+-      rm $tmp
+-   else
+-      echo "tvservice not installed"
+-   fi
+-
+-   if pgrep Xorg > /dev/null &&
+-      command -v xrandr > /dev/null &&
+-      DISPLAY=${DISPLAY:-:0} xrandr --listmonitors >/dev/null 2>&1; then
+-      DISPLAY=${DISPLAY:-:0} xrandr --verbose
 -      echo
--      echo "Display: " $display
--
--      tvservice -v $display -s
--      tvservice -v $display -n
--      tvservice -v $display -m CEA
--      tvservice -v $display -m DMT
--
--      echo
--      tvservice -v $display -d $tmp > /dev/null
--      base64 $tmp
--   done
--
--   rm $tmp
+-   fi
 -}
 -
 -display_info() {
 -   # Check if we are running a KMS/DRM system
+-
+-   if [ -f /proc/device-tree/soc/firmwarekms@*/status ] &&
+-      grep -q okay /proc/device-tree/soc/firmwarekms@*/status; then
+-      KMS=fkms
+-   elif [ -f /proc/device-tree/*/v3d@*/status ] &&
+-      grep -q okay /proc/device-tree/*/v3d@*/status; then
+-      KMS=kms
+-   else
+-      KMS=legacy
+-   fi
+-
+-   if pgrep labwc > /dev/null; then
+-      WIN=labwc
+-   elif pgrep wayfire > /dev/null; then
+-      WIN=wayfire
+-   elif pgrep Xorg > /dev/null; then
+-      WIN=Xorg
+-   else
+-      WIN=console
+-   fi
+-   echo "Using $WIN with $KMS"
 -
 -   if [ -d "/dev/dri" ];
 -   then
@@ -164,10 +177,36 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
 -   fi
 -}
 -
- OUT=raspinfo.txt
+ network_info() {
+    cat /proc/net/wireless 2>/dev/null || echo "/proc/net/wireless not available"
+    echo
+    if command -v rfkill >/dev/null; then
+       rfkill list
+    else
+-      echo "rfkill not installed"
++      echo "rfkill not found"
+    fi
+    echo
  
- rm -f $OUT
-@@ -163,8 +22,6 @@ echo
+@@ -188,7 +28,7 @@ network_info() {
+             if [ -d "$iface/phy80211" ]; then
+                ethtool -i $iface_name
+             else
+-               sudo ethtool $iface_name
++               ethtool $iface_name
+                echo
+                ethtool --show-eee $iface_name
+                echo
+@@ -198,7 +38,7 @@ network_info() {
+          fi
+       done
+    else
+-      echo "ethtool not installed"
++      echo "ethtool not found"
+    fi
+ }
+ 
+@@ -222,8 +62,6 @@ echo
  cat /etc/os-release | head -4
  echo
  
@@ -176,12 +215,13 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
  uname -a
  
  cat /proc/cpuinfo | tail -3
-@@ -190,17 +47,6 @@ echo
+@@ -260,18 +98,6 @@ echo
  cat /proc/swaps
  
  echo
 -echo "Package version information"
 -echo "---------------------------"
+-echo
 -
 -apt-cache policy raspberrypi-ui-mods | head -2
 -apt-cache policy raspberrypi-sys-mods | head -2
@@ -194,7 +234,7 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
  echo "Networking Information"
  echo "----------------------"
  echo
-@@ -212,21 +58,11 @@ echo "USB Information"
+@@ -283,21 +109,11 @@ echo "USB Information"
  echo "---------------"
  echo
  
@@ -214,14 +254,14 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
 -
 -audio_info
 +if command -v lsusb > /dev/null; then
-+   lsusb -t
++   lsusb -t 2>&1
 +else
-+   echo usbutils not installed
++   echo "usbutils not found"
 +fi
  
  echo
- echo "config.txt"
-@@ -250,7 +86,7 @@ echo "-----------------"
+ echo "Firmware Configuration"
+@@ -322,7 +138,7 @@ echo "-----------------"
  echo
  
  if command -v pinctrl > /dev/null; then
@@ -230,7 +270,7 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
  elif command -v raspi-gpio > /dev/null; then
     raspi-gpio get 2>&1
  else
-@@ -263,9 +99,9 @@ echo "------------------"
+@@ -335,9 +151,9 @@ echo "------------------"
  echo
  
  if command -v vcdbg > /dev/null; then
@@ -242,14 +282,23 @@ Signed-off-by: Álvaro Fernández Rojas <noltari@gmail.com>
  else
     echo "vcdbg not found"
  fi
-@@ -284,5 +120,9 @@ echo
- echo "EEPROM"
- echo "------"
+@@ -347,16 +163,16 @@ echo "dmesg log"
+ echo "---------"
  echo
--sudo rpi-eeprom-update
-+if command -v rpi-eeprom-update > /dev/null; then
-+   rpi-eeprom-update
-+else
-+   echo bcm27xx-eeprom not installed
-+fi
- fi
+ 
+-sudo dmesg | filter
++dmesg | filter
+ 
+-if  grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]1[13457][0-9a-fA-F]$" /proc/cpuinfo
++if  grep -q "^Revision\s*:\s*[ 123][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]1[0-9][0-9a-fA-F]$" /proc/cpuinfo
+ then
+    echo
+    echo "EEPROM"
+    echo "------"
+    echo
+    if command -v rpi-eeprom-update > /dev/null; then
+-      sudo rpi-eeprom-update
++      rpi-eeprom-update
+    else
+       echo "rpi-eeprom-update not found"
+    fi
